# Generated by Django 3.2.6 on 2021-10-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trendingsong',
            fields=[
                ('trend_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_id', models.CharField(max_length=200000000)),
                ('name', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=500)),
                ('count', models.BigIntegerField()),
            ],
        ),
    ]
