# Generated by Django 3.2.6 on 2021-10-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0003_auto_20211001_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trendingsinger',
            fields=[
                ('trend_id', models.AutoField(primary_key=True, serialize=False)),
                ('sing_id', models.CharField(max_length=2000)),
                ('count', models.BigIntegerField()),
            ],
        ),
    ]
