# Generated by Django 3.2.6 on 2021-10-01 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicbeats', '0004_trendingsinger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('song_id', models.ManyToManyField(related_name='playlist', to='musicbeats.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
